accounting:
  slurmdbd:
    image:
      repository: quay.io/slinky-on-openshift/slurmdbd
      tag: 25.11-centos9-ohpc
configFiles:
  gres.conf: AutoDetect=nvidia
controller:
  reconfigure:
    image:
      repository: quay.io/slinky-on-openshift/slurmctld
      tag: 25.11-centos9-ohpc
  slurmctld:
    image:
      repository: quay.io/slinky-on-openshift/slurmctld
      tag: 25.11-centos9-ohpc
loginsets:
  slinky:
    enabled: true
    login:
      image:
        repository: quay.io/slinky-on-openshift/login
        tag: 25.11-centos9-ohpc
      securityContext:
        privileged: true
      volumeMounts:
        - name: shared-home
          mountPath: /home
    podSpec:
      volumes:
        - name: shared-home
          persistentVolumeClaim:
            claimName: shared-home
nodesets:
  slinky:
    replicas: 1
    slurmd:
      image:
        repository: quay.io/slinky-on-openshift/slurmd-cuda
        tag: 25.11-centos9-ohpc
      resources:
        limits:
          nvidia.com/gpu: 1
        requests:
          nvidia.com/gpu: 1
      volumeMounts:
        - name: shared-home
          mountPath: /home
    podSpec:
      volumes:
        - name: shared-home
          persistentVolumeClaim:
            claimName: shared-home
restapi:
  slurmrestd:
    image:
      repository: quay.io/slinky-on-openshift/slurmrestd
      tag: 25.11-centos9-ohpc
